services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared
    container_name: cloudflare-tunnel
    hostname: cloudflare-tunnel
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    command: tunnel run
    volumes:
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "cloudflared", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
      POSTGRES_DB: rezervariCamin
    volumes:
    - ../appdata/spalatorie/db:/var/lib/postgresql
  adminer:
    image: adminer
    restart: always
    ports:
    - 8030:8080
  backend:
    image: blitzcloud/camin:0.0.3
    restart: always
    depends_on:
      - db
    ports:
      - 8881:8881
    env_file:
      - ./.env
